export const REQUEST_LOCATION = "REQUEST_LOCATION";
export const REQUEST_LOCATION_FAILED = "REQUEST_LOCATION_FAILED";
export const RECEIVE_LOCATION = "RECEIVE_LOCATION";

export const REQUEST_FAVORITE_LOCATIONS = "REQUEST_FAVORITE_LOCATIONS";
export const REQUEST_FAVORITE_LOCATIONS_FAILED = "REQUEST_FAVORITE_LOCATIONS_FAILED";
export const RECEIVE_FAVORITE_LOCATIONS = "RECEIVE_FAVORITE_LOCATIONS";

export const REQUEST_FREQUENT_LOCATIONS = "REQUEST_FREQUENT_LOCATIONS";
export const REQUEST_FREQUENT_LOCATIONS_FAILED = "REQUEST_FREQUENT_LOCATIONS_FAILED";
export const RECEIVE_FREQUENT_LOCATIONS = "RECEIVE_FREQUENT_LOCATIONS";
