export const REQUEST_WEATHER = "REQUEST_WEATHER";
export const REQUEST_WEATHER_FAILED = "REQUEST_WEATHER_FAILED";
export const RECEIVE_WEATHER = "RECEIVE_WEATHER";

export const REQUEST_FORECAST = "REQUEST_FORECAST";
export const REQUEST_FORECAST_FAILED = "REQUEST_FORECAST_FAILED";
export const RECEIVE_FORECAST = "RECEIVE_FORECAST";


