export const LOGIN = "LOGIN";
export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const REQUEST_LOGIN_FAILED = "REQUEST_LOGIN_FAILED";

export const REGISTER = "REGISTER";
export const REQUEST_REGISTER = "REQUEST_REGISTER";
export const REQUEST_REGISTER_FAILED = "REQUEST_REGISTER_FAILED";
